### ISSUE TITLE
Question: what is the difference between beyondcode/nova-filterable-cards package?

### ISSUE THREAD

**Issue by lptn** [nemrutco/nova-filterable-metrics#3]
https://github.com/beyondcode/nova-filterable-cards

**Comment by nemrutco** [comment]
there are few differences:

- You can use your existing filters and apply them on your metrics same way as you apply on your resources. (Nova friendly) 
- There is a date-range field instead of fixed days range. 
- It is based on Nova 2.0^ (i couldn't compile beyondcode's package i believe it is out of date) 
...

there are some issues which i can't remember and couldn't deal with them so i decided to go with this package. I wish i can send a pr to beyondcode's package but I couldn't get any response from them. 

PS: there is a better package implemented already even i already changed in my own projects :) 
[https://github.com/square1-io/nova-metrics]https://github.com/square1-io/nova-metrics

**Comment by lptn** [comment]
thanks a lot!
